import { SectionHeader } from "@/components/ui/SectionHeader";
import { FoldsFilter } from "@/components/folds/FoldsFilter";
import { FoldsCatalog } from "@/components/folds/FoldsCatalog";
import { Pagination } from "@/components/folds/Pagination";
import { listFolds, type FoldsQuery } from "@/lib/api";

export const dynamic = "force-dynamic";

const PAGE_SIZE = 12;

interface FoldsPageProps {
  searchParams: {
    search?: string;
    peptide_class?: string;
    status?: string;
    min_confidence?: string;
    sort?: string;
    page?: string;
  };
}

const ALLOWED_SORTS = new Set([
  "newest",
  "oldest",
  "highest_confidence",
  "lowest_confidence",
]);

function normalizeSort(value: string | undefined): FoldsQuery["sort"] {
  if (value && ALLOWED_SORTS.has(value)) return value as FoldsQuery["sort"];
  // map legacy ui values
  if (value === "confidence_desc") return "highest_confidence";
  if (value === "confidence_asc") return "lowest_confidence";
  return "newest";
}

export default async function FoldsPage({ searchParams }: FoldsPageProps) {
  const page = Math.max(1, parseInt(searchParams.page ?? "1", 10) || 1);
  const minConfidence = searchParams.min_confidence
    ? Math.max(0, Math.min(1, parseFloat(searchParams.min_confidence)))
    : undefined;

  let response;
  try {
    response = await listFolds({
      peptide_class: searchParams.peptide_class,
      status: searchParams.status,
      search: searchParams.search?.trim() || undefined,
      min_confidence: Number.isFinite(minConfidence) ? minConfidence : undefined,
      sort: normalizeSort(searchParams.sort),
      page,
      page_size: PAGE_SIZE,
    });
  } catch {
    response = {
      items: [],
      total: 0,
      page: 1,
      page_size: PAGE_SIZE,
      total_pages: 1,
    };
  }

  // Filtering is now fully server-side — see ``listFolds()``. We just render
  // whatever the backend returned for this page.
  const visible = response.items;
  const total = response.total;
  const totalPages = Math.max(1, response.total_pages);
  const start = (page - 1) * PAGE_SIZE;

  return (
    <div>
      <h1 className="text-h1 sm:text-display font-bold uppercase tracking-wider">
        folds
      </h1>
      <p className="mt-3 text-text-secondary text-body max-w-2xl leading-relaxed">
        autonomous peptide research log. browse the full catalog of folds
        generated by the lab. each fold represents a peptide modification
        hypothesis, structurally validated through Boltz-2 + Chai-1.
      </p>

      <div className="mt-12">
        <SectionHeader index="01" title="filter" />
        <FoldsFilter />
      </div>

      <div className="mt-16">
        <SectionHeader
          index="02"
          title="catalog"
          trailing={
            total === 0
              ? "no matches"
              : `showing ${start + 1}–${Math.min(start + PAGE_SIZE, total)} of ${total}`
          }
        />
        {total === 0 ? (
          <p className="text-text-muted text-small italic">
            {`// no folds yet — the lab is distilling. cycles run continuously.`}
          </p>
        ) : (
          <>
            <FoldsCatalog folds={visible} />
            <div className="mt-10">
              <Pagination
                page={page}
                totalPages={totalPages}
                basePath="/folds"
                query={searchParams}
              />
            </div>
          </>
        )}
      </div>
    </div>
  );
}
